### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by chrisvfritz** [spalot/codelab-html-intro#1]
@chrisvfritz Take a look at this.

**Comment by chrisvfritz** [comment]
I see a few things that aren't quite right, but we're most of the way there!

First, [this image tag](https://github.com/spalot/codelab-html-intro/blob/master/index.html#L8) has a few errors that the web browser is compensating for. 

``` html
<img src="americanize.jpg" alt="My First 10 years"width=400"" height="200"/>
```

Above, there should be a space before `width` and there's also an extra quote after `400`.

One other error I see is that [your ordered list (`ol`)](https://github.com/spalot/codelab-html-intro/blob/master/index.html#L10) doesn't have a closing tag.

And that's it! When you push up your new version with surge, you can use [the W3C validator](https://validator.w3.org/) to make sure that your site doesn't have any errors on it. :smiley:

**Comment by chrisvfritz** [comment]
:tada: :rocket: :balloon: :shipit:

**Comment by spalot** [comment]
Thanks!
